;; Trade Document Manager
(define-constant err-not-found (err u101))
(define-constant err-unauthorized (err u103))
(define-data-var doc-counter uint u0)
(define-data-var lc-counter uint u0)
(define-map documents uint {exporter: principal, importer: principal, doc-type: uint, hash: (string-ascii 64), verified: bool, timestamp: uint})
(define-map letters-of-credit uint {issuing-bank: principal, beneficiary: principal, amount: uint, terms: (string-ascii 200), status: uint, expiry: uint})
(define-map shipments uint {doc-id: uint, carrier: (string-ascii 100), tracking: (string-ascii 50), departure: uint, arrival: uint, delivered: bool})
(define-map payments uint {lc-id: uint, payer: principal, payee: principal, amount: uint, released: bool, timestamp: uint})
(define-read-only (get-document (id uint)) (ok (map-get? documents id)))
(define-read-only (get-lc (id uint)) (ok (map-get? letters-of-credit id)))
(define-public (create-document (importer principal) (doc-type uint) (hash (string-ascii 64)))
  (let ((id (+ (var-get doc-counter) u1)))
    (map-set documents id {exporter: tx-sender, importer: importer, doc-type: doc-type, hash: hash, verified: false, timestamp: block-height})
    (var-set doc-counter id) (ok id)))
(define-public (verify-document (doc-id uint))
  (let ((doc (unwrap! (map-get? documents doc-id) err-not-found)))
    (asserts! (is-eq (get importer doc) tx-sender) err-unauthorized)
    (map-set documents doc-id (merge doc {verified: true})) (ok true)))
(define-public (issue-lc (beneficiary principal) (amount uint) (terms (string-ascii 200)) (validity uint))
  (let ((id (+ (var-get lc-counter) u1)))
    (map-set letters-of-credit id {issuing-bank: tx-sender, beneficiary: beneficiary, amount: amount, terms: terms, status: u1, expiry: (+ block-height validity)})
    (var-set lc-counter id) (ok id)))
(define-public (record-shipment (doc-id uint) (carrier (string-ascii 100)) (tracking (string-ascii 50)) (arrival uint))
  (let ((doc (unwrap! (map-get? documents doc-id) err-not-found)))
    (asserts! (is-eq (get exporter doc) tx-sender) err-unauthorized)
    (map-set shipments doc-id {doc-id: doc-id, carrier: carrier, tracking: tracking, departure: block-height, arrival: arrival, delivered: false})
    (ok true)))
(define-public (release-payment (lc-id uint))
  (let ((lc (unwrap! (map-get? letters-of-credit lc-id) err-not-found)))
    (asserts! (is-eq (get issuing-bank lc) tx-sender) err-unauthorized)
    (try! (stx-transfer? (get amount lc) tx-sender (get beneficiary lc)))
    (map-set letters-of-credit lc-id (merge lc {status: u2})) (ok true)))
